FROM node:13.12.0-stretch

RUN wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -P /home/node/ngrok/ && \
    unzip /home/node/ngrok/ngrok-stable-linux-amd64.zip -d /home/node/ngrok/ && \
    rm /home/node/ngrok/ngrok-stable-linux-amd64.zip